// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: LVGL_BIKE

#include "../ui.h"

void ui_GPSApp_screen_init(void)
{
    ui_GPSApp = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_GPSApp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GPS_Back_Btn = lv_btn_create(ui_GPSApp);
    lv_obj_set_width(ui_GPS_Back_Btn, 48);
    lv_obj_set_height(ui_GPS_Back_Btn, 32);
    lv_obj_set_x(ui_GPS_Back_Btn, 12);
    lv_obj_set_y(ui_GPS_Back_Btn, 8);
    lv_obj_add_flag(ui_GPS_Back_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GPS_Back_Btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GPS_Back_Btn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GPS_Back_Btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GPS_Back_Btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GPS_Back_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GPS_Back_Btn, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GPS_Back_Btn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_GPS_Back_Btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_GPS_Back_Btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_GPS_Back_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GPS_Back_Btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GPS_Back_Btn, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPS_Back_Btn_Label = lv_label_create(ui_GPS_Back_Btn);
    lv_obj_set_width(ui_GPS_Back_Btn_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPS_Back_Btn_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GPS_Back_Btn_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GPS_Back_Btn_Label, "^");

    ui_GPS_Status_Label = lv_label_create(ui_GPSApp);
    lv_obj_set_width(ui_GPS_Status_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPS_Status_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GPS_Status_Label, 104);
    lv_obj_set_y(ui_GPS_Status_Label, 9);
    lv_label_set_text(ui_GPS_Status_Label, "ALL GREAT");
    lv_obj_set_style_text_color(ui_GPS_Status_Label, lv_color_hex(0x82CD47), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GPS_Status_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GPS_Status_Label, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPS_Main = lv_obj_create(ui_GPSApp);
    lv_obj_set_width(ui_GPS_Main, 296);
    lv_obj_set_height(ui_GPS_Main, 180);
    lv_obj_set_x(ui_GPS_Main, 0);
    lv_obj_set_y(ui_GPS_Main, 18);
    lv_obj_set_align(ui_GPS_Main, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GPS_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GPS_Main, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPS_Main_Sat_Icon = lv_label_create(ui_GPS_Main);
    lv_obj_set_width(ui_GPS_Main_Sat_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPS_Main_Sat_Icon, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_GPS_Main_Sat_Icon, "O");
    lv_obj_set_style_text_font(ui_GPS_Main_Sat_Icon, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPS_Main_Sat_Label = lv_label_create(ui_GPS_Main);
    lv_obj_set_width(ui_GPS_Main_Sat_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPS_Main_Sat_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GPS_Main_Sat_Label, 24);
    lv_obj_set_y(ui_GPS_Main_Sat_Label, 0);
    lv_label_set_text(ui_GPS_Main_Sat_Label, "Satellites:");
    lv_obj_set_style_text_font(ui_GPS_Main_Sat_Label, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPS_Main_Sat_Value = lv_label_create(ui_GPS_Main);
    lv_obj_set_width(ui_GPS_Main_Sat_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPS_Main_Sat_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GPS_Main_Sat_Value, 104);
    lv_obj_set_y(ui_GPS_Main_Sat_Value, 0);
    lv_label_set_text(ui_GPS_Main_Sat_Value, "3");
    lv_obj_set_style_text_font(ui_GPS_Main_Sat_Value, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPS_Main_Lat_Icon = lv_label_create(ui_GPS_Main);
    lv_obj_set_width(ui_GPS_Main_Lat_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPS_Main_Lat_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GPS_Main_Lat_Icon, 0);
    lv_obj_set_y(ui_GPS_Main_Lat_Icon, 32);
    lv_label_set_text(ui_GPS_Main_Lat_Icon, "O");
    lv_obj_set_style_text_font(ui_GPS_Main_Lat_Icon, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPS_Main_Lat_Label = lv_label_create(ui_GPS_Main);
    lv_obj_set_width(ui_GPS_Main_Lat_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPS_Main_Lat_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GPS_Main_Lat_Label, 24);
    lv_obj_set_y(ui_GPS_Main_Lat_Label, 32);
    lv_label_set_text(ui_GPS_Main_Lat_Label, "Latitude:");
    lv_obj_set_style_text_font(ui_GPS_Main_Lat_Label, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPS_Main_Lat_Value = lv_label_create(ui_GPS_Main);
    lv_obj_set_width(ui_GPS_Main_Lat_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPS_Main_Lat_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GPS_Main_Lat_Value, 104);
    lv_obj_set_y(ui_GPS_Main_Lat_Value, 32);
    lv_label_set_text(ui_GPS_Main_Lat_Value, "0.0000");
    lv_obj_set_style_text_font(ui_GPS_Main_Lat_Value, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPS_Main_Lon_Icon = lv_label_create(ui_GPS_Main);
    lv_obj_set_width(ui_GPS_Main_Lon_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPS_Main_Lon_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GPS_Main_Lon_Icon, 0);
    lv_obj_set_y(ui_GPS_Main_Lon_Icon, 64);
    lv_label_set_text(ui_GPS_Main_Lon_Icon, "O");
    lv_obj_set_style_text_font(ui_GPS_Main_Lon_Icon, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPS_Main_Lon_Label = lv_label_create(ui_GPS_Main);
    lv_obj_set_width(ui_GPS_Main_Lon_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPS_Main_Lon_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GPS_Main_Lon_Label, 24);
    lv_obj_set_y(ui_GPS_Main_Lon_Label, 64);
    lv_label_set_text(ui_GPS_Main_Lon_Label, "Longtitude:");
    lv_obj_set_style_text_font(ui_GPS_Main_Lon_Label, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPS_Main_Lon_Value = lv_label_create(ui_GPS_Main);
    lv_obj_set_width(ui_GPS_Main_Lon_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPS_Main_Lon_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GPS_Main_Lon_Value, 128);
    lv_obj_set_y(ui_GPS_Main_Lon_Value, 64);
    lv_label_set_text(ui_GPS_Main_Lon_Value, "0.0000");
    lv_obj_set_style_text_font(ui_GPS_Main_Lon_Value, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPS_Main_Time_Icon = lv_label_create(ui_GPS_Main);
    lv_obj_set_width(ui_GPS_Main_Time_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPS_Main_Time_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GPS_Main_Time_Icon, 0);
    lv_obj_set_y(ui_GPS_Main_Time_Icon, 96);
    lv_label_set_text(ui_GPS_Main_Time_Icon, "O");
    lv_obj_set_style_text_font(ui_GPS_Main_Time_Icon, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPS_Main_Time_Label = lv_label_create(ui_GPS_Main);
    lv_obj_set_width(ui_GPS_Main_Time_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPS_Main_Time_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GPS_Main_Time_Label, 24);
    lv_obj_set_y(ui_GPS_Main_Time_Label, 96);
    lv_label_set_text(ui_GPS_Main_Time_Label, "GPS Time:");
    lv_obj_set_style_text_font(ui_GPS_Main_Time_Label, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPS_Main_Time_Value = lv_label_create(ui_GPS_Main);
    lv_obj_set_width(ui_GPS_Main_Time_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPS_Main_Time_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GPS_Main_Time_Value, 112);
    lv_obj_set_y(ui_GPS_Main_Time_Value, 96);
    lv_label_set_text(ui_GPS_Main_Time_Value, "18:41:00");
    lv_obj_set_style_text_font(ui_GPS_Main_Time_Value, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPS_Status_Icon = lv_label_create(ui_GPSApp);
    lv_obj_set_width(ui_GPS_Status_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPS_Status_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GPS_Status_Icon, 72);
    lv_obj_set_y(ui_GPS_Status_Icon, 9);
    lv_label_set_text(ui_GPS_Status_Icon, "O");
    lv_obj_set_style_text_color(ui_GPS_Status_Icon, lv_color_hex(0x82CD47), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GPS_Status_Icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GPS_Status_Icon, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_GPS_Back_Btn, ui_event_GPS_Back_Btn, LV_EVENT_ALL, NULL);

}
