// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: LVGL_BIKE

#include "../ui.h"

void ui_MainApp_screen_init(void)
{
    ui_MainApp = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainApp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Main_Bat_bg = lv_obj_create(ui_MainApp);
    lv_obj_set_width(ui_Main_Bat_bg, 110);
    lv_obj_set_height(ui_Main_Bat_bg, 100);
    lv_obj_set_x(ui_Main_Bat_bg, 65);
    lv_obj_set_y(ui_Main_Bat_bg, 15);
    lv_obj_clear_flag(ui_Main_Bat_bg, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Main_Bat_bg, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Main_Bat_bg, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_Bat_bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_Bat_Lv = lv_label_create(ui_Main_Bat_bg);
    lv_obj_set_width(ui_Main_Bat_Lv, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_Bat_Lv, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Main_Bat_Lv, 0);
    lv_obj_set_y(ui_Main_Bat_Lv, 2);
    lv_obj_set_align(ui_Main_Bat_Lv, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Main_Bat_Lv, "100");
    lv_label_set_recolor(ui_Main_Bat_Lv, "true");
    lv_obj_clear_flag(ui_Main_Bat_Lv, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Main_Bat_Lv, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Main_Bat_Lv, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Main_Bat_Lv, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Main_Bat_Lv, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_Charge_Icon = lv_label_create(ui_Main_Bat_bg);
    lv_obj_set_width(ui_Main_Charge_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_Charge_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Main_Charge_Icon, 50);
    lv_obj_set_y(ui_Main_Charge_Icon, 35);
    lv_label_set_text(ui_Main_Charge_Icon, "S");
    lv_obj_clear_flag(ui_Main_Charge_Icon,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Main_Charge_Icon, lv_color_hex(0xFFD400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Main_Charge_Icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Main_Charge_Icon, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_Charge_Prog = lv_bar_create(ui_Main_Bat_bg);
    lv_bar_set_value(ui_Main_Charge_Prog, 10, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Main_Charge_Prog, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Main_Charge_Prog, 30);
    lv_obj_set_height(ui_Main_Charge_Prog, 75);
    lv_obj_set_x(ui_Main_Charge_Prog, 2);
    lv_obj_set_y(ui_Main_Charge_Prog, -3);
    lv_obj_clear_flag(ui_Main_Charge_Prog,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Main_Charge_Prog, lv_color_hex(0x08FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_Charge_Prog, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Main_Charge_Prog, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Main_Charge_Prog, lv_color_hex(0x08FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_Charge_Prog, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Main_Light2 = lv_obj_create(ui_MainApp);
    lv_obj_set_width(ui_Main_Light2, 50);
    lv_obj_set_height(ui_Main_Light2, 170);
    lv_obj_set_x(ui_Main_Light2, -20);
    lv_obj_set_y(ui_Main_Light2, 20);
    lv_obj_set_align(ui_Main_Light2, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Main_Light2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Main_Light2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_Light2_Slider = lv_slider_create(ui_Main_Light2);
    lv_slider_set_value(ui_Main_Light2_Slider, 1, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Main_Light2_Slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Main_Light2_Slider, 0,
                                                                                                       LV_ANIM_OFF);
    lv_obj_set_width(ui_Main_Light2_Slider, 25);
    lv_obj_set_height(ui_Main_Light2_Slider, 120);
    lv_obj_set_align(ui_Main_Light2_Slider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Main_Light2_Slider, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_Light2_Slider, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Main_Light2_Slider, lv_color_hex(0xE8C872), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_Light2_Slider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Main_Light2_Slider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_Light2_Slider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Main_Light2_Slider, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Main_Light2_Slider, 125, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Main_Light2_Slider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Main_Light2_Slider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Main_Light2_Slider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Main_Light2_Slider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Main_Light2_Slider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Main_Light2_Slider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Main_Light1 = lv_obj_create(ui_MainApp);
    lv_obj_set_width(ui_Main_Light1, 50);
    lv_obj_set_height(ui_Main_Light1, 170);
    lv_obj_set_x(ui_Main_Light1, -82);
    lv_obj_set_y(ui_Main_Light1, 20);
    lv_obj_set_align(ui_Main_Light1, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Main_Light1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Main_Light1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_Light1_Slider = lv_slider_create(ui_Main_Light1);
    lv_slider_set_value(ui_Main_Light1_Slider, 1, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Main_Light1_Slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Main_Light1_Slider, 0,
                                                                                                       LV_ANIM_OFF);
    lv_obj_set_width(ui_Main_Light1_Slider, 25);
    lv_obj_set_height(ui_Main_Light1_Slider, 120);
    lv_obj_set_align(ui_Main_Light1_Slider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Main_Light1_Slider, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_Light1_Slider, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Main_Light1_Slider, lv_color_hex(0xE8C872), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_Light1_Slider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Main_Light1_Slider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_Light1_Slider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Main_Light1_Slider, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Main_Light1_Slider, 125, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Main_Light1_Slider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Main_Light1_Slider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Main_Light1_Slider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Main_Light1_Slider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Main_Light1_Slider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Main_Light1_Slider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Main_Light1_Swt = lv_switch_create(ui_MainApp);
    lv_obj_set_width(ui_Main_Light1_Swt, 40);
    lv_obj_set_height(ui_Main_Light1_Swt, 25);
    lv_obj_set_x(ui_Main_Light1_Swt, 51);
    lv_obj_set_y(ui_Main_Light1_Swt, 20);
    lv_obj_set_align(ui_Main_Light1_Swt, LV_ALIGN_TOP_MID);

    lv_obj_set_style_bg_color(ui_Main_Light1_Swt, lv_color_hex(0xE8C872), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Main_Light1_Swt, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_Main_Light2_Swt = lv_switch_create(ui_MainApp);
    lv_obj_set_width(ui_Main_Light2_Swt, 40);
    lv_obj_set_height(ui_Main_Light2_Swt, 25);
    lv_obj_set_x(ui_Main_Light2_Swt, 113);
    lv_obj_set_y(ui_Main_Light2_Swt, 20);
    lv_obj_set_align(ui_Main_Light2_Swt, LV_ALIGN_TOP_MID);

    lv_obj_set_style_bg_color(ui_Main_Light2_Swt, lv_color_hex(0xE8C872), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Main_Light2_Swt, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_Main_Speed = lv_obj_create(ui_MainApp);
    lv_obj_set_width(ui_Main_Speed, 110);
    lv_obj_set_height(ui_Main_Speed, 100);
    lv_obj_set_x(ui_Main_Speed, 65);
    lv_obj_set_y(ui_Main_Speed, -15);
    lv_obj_set_align(ui_Main_Speed, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_Main_Speed, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Main_Speed, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Main_Speed, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_Speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_Speed_Arc = lv_arc_create(ui_Main_Speed);
    lv_obj_set_width(ui_Main_Speed_Arc, 80);
    lv_obj_set_height(ui_Main_Speed_Arc, 80);
    lv_obj_set_x(ui_Main_Speed_Arc, 0);
    lv_obj_set_y(ui_Main_Speed_Arc, 5);
    lv_obj_set_align(ui_Main_Speed_Arc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Main_Speed_Arc,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_range(ui_Main_Speed_Arc, 0, 40);
    lv_arc_set_value(ui_Main_Speed_Arc, 2);
    lv_obj_set_style_arc_color(ui_Main_Speed_Arc, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Main_Speed_Arc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Main_Speed_Arc, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Main_Speed_Arc, lv_color_hex(0xD20000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Main_Speed_Arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Main_Speed_Arc, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Main_Speed_Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_Speed_Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Main_Speed_Label = lv_label_create(ui_Main_Speed_Arc);
    lv_obj_set_width(ui_Main_Speed_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_Speed_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Main_Speed_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_Speed_Label, "2");
    lv_obj_clear_flag(ui_Main_Speed_Label,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Main_Speed_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Main_Speed_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Main_Speed_Label, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_Dock = lv_obj_create(ui_MainApp);
    lv_obj_set_width(ui_Main_Dock, 75);
    lv_obj_set_height(ui_Main_Dock, 208);
    lv_obj_set_x(ui_Main_Dock, -144);
    lv_obj_set_y(ui_Main_Dock, 0);
    lv_obj_set_align(ui_Main_Dock, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Main_Dock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Main_Dock, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_RoadApp = lv_btn_create(ui_MainApp);
    lv_obj_set_width(ui_Main_RoadApp, 40);
    lv_obj_set_height(ui_Main_RoadApp, 40);
    lv_obj_set_x(ui_Main_RoadApp, -137);
    lv_obj_set_y(ui_Main_RoadApp, -72);
    lv_obj_set_align(ui_Main_RoadApp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Main_RoadApp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Main_RoadApp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Main_RoadApp, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Main_RoadApp, lv_color_hex(0x76885B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_RoadApp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Main_RoadApp, lv_color_hex(0x00C204), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Main_RoadApp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_RoadApp_Icon = lv_label_create(ui_Main_RoadApp);
    lv_obj_set_width(ui_Main_RoadApp_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_RoadApp_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Main_RoadApp_Icon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_RoadApp_Icon, "R");
    lv_obj_set_style_text_color(ui_Main_RoadApp_Icon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Main_RoadApp_Icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Main_RoadApp_Icon, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_SetApp = lv_btn_create(ui_MainApp);
    lv_obj_set_width(ui_Main_SetApp, 40);
    lv_obj_set_height(ui_Main_SetApp, 40);
    lv_obj_set_x(ui_Main_SetApp, -137);
    lv_obj_set_y(ui_Main_SetApp, -24);
    lv_obj_set_align(ui_Main_SetApp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Main_SetApp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Main_SetApp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Main_SetApp, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Main_SetApp, lv_color_hex(0x31363F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_SetApp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Main_SetApp, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Main_SetApp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_SetApp_Icon = lv_label_create(ui_Main_SetApp);
    lv_obj_set_width(ui_Main_SetApp_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_SetApp_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Main_SetApp_Icon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_SetApp_Icon, "S");
    lv_obj_set_style_text_font(ui_Main_SetApp_Icon, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_NaviApp = lv_btn_create(ui_MainApp);
    lv_obj_set_width(ui_Main_NaviApp, 40);
    lv_obj_set_height(ui_Main_NaviApp, 40);
    lv_obj_set_x(ui_Main_NaviApp, -137);
    lv_obj_set_y(ui_Main_NaviApp, 24);
    lv_obj_set_align(ui_Main_NaviApp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Main_NaviApp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Main_NaviApp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Main_NaviApp, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Main_NaviApp, lv_color_hex(0xE72929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_NaviApp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Main_NaviApp, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Main_NaviApp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_NaviApp_Icon = lv_label_create(ui_Main_NaviApp);
    lv_obj_set_width(ui_Main_NaviApp_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_NaviApp_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Main_NaviApp_Icon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_NaviApp_Icon, "N");
    lv_obj_set_style_text_color(ui_Main_NaviApp_Icon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Main_NaviApp_Icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Main_NaviApp_Icon, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_ClockApp = lv_btn_create(ui_MainApp);
    lv_obj_set_width(ui_Main_ClockApp, 40);
    lv_obj_set_height(ui_Main_ClockApp, 40);
    lv_obj_set_x(ui_Main_ClockApp, -137);
    lv_obj_set_y(ui_Main_ClockApp, 72);
    lv_obj_set_align(ui_Main_ClockApp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Main_ClockApp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Main_ClockApp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Main_ClockApp, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Main_ClockApp, lv_color_hex(0x474F7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_ClockApp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Main_ClockApp, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Main_ClockApp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_ClockApp_Icon = lv_label_create(ui_Main_ClockApp);
    lv_obj_set_width(ui_Main_ClockApp_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_ClockApp_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Main_ClockApp_Icon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_ClockApp_Icon, "C");
    lv_obj_set_style_text_color(ui_Main_ClockApp_Icon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Main_ClockApp_Icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Main_ClockApp_Icon, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Main_RoadApp, ui_event_Main_RoadApp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Main_SetApp, ui_event_Main_SetApp, LV_EVENT_ALL, NULL);

}
