// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: LVGL_BIKE

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Speedometer2 = lv_obj_create(ui_Screen2);
lv_obj_set_width( ui_Speedometer2, 150);
lv_obj_set_height( ui_Speedometer2, 150);
lv_obj_set_x( ui_Speedometer2, 16 );
lv_obj_set_y( ui_Speedometer2, 16 );
lv_obj_clear_flag( ui_Speedometer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_Speedometer2, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Speedometer_Arc1 = lv_arc_create(ui_Speedometer2);
lv_obj_set_width( ui_Speedometer_Arc1, 120);
lv_obj_set_height( ui_Speedometer_Arc1, 120);
lv_obj_set_x( ui_Speedometer_Arc1, 0 );
lv_obj_set_y( ui_Speedometer_Arc1, 5 );
lv_obj_set_align( ui_Speedometer_Arc1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Speedometer_Arc1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_arc_set_range(ui_Speedometer_Arc1, 0,40);
lv_arc_set_value(ui_Speedometer_Arc1, 2);
lv_obj_set_style_arc_color(ui_Speedometer_Arc1, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Speedometer_Arc1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Speedometer_Arc1, 12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Speedometer_Arc1, lv_color_hex(0xD20000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Speedometer_Arc1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Speedometer_Arc1, 12, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Speedometer_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Speedometer_Arc1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Speedometer_Label1 = lv_label_create(ui_Speedometer_Arc1);
lv_obj_set_width( ui_Speedometer_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Speedometer_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Speedometer_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Speedometer_Label1,"2");
lv_obj_clear_flag( ui_Speedometer_Label1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Speedometer_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Speedometer_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Speedometer_Label1, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Kmh_label = lv_label_create(ui_Speedometer_Arc1);
lv_obj_set_width( ui_Kmh_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Kmh_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Kmh_label, 0 );
lv_obj_set_y( ui_Kmh_label, 48 );
lv_obj_set_align( ui_Kmh_label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Kmh_label,"km/h");

ui_Distance = lv_obj_create(ui_Screen2);
lv_obj_set_width( ui_Distance, 128);
lv_obj_set_height( ui_Distance, 80);
lv_obj_set_x( ui_Distance, 176 );
lv_obj_set_y( ui_Distance, 16 );
lv_obj_clear_flag( ui_Distance, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Distance, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Dist_label = lv_label_create(ui_Distance);
lv_obj_set_width( ui_Dist_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Dist_label, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_Dist_label,"Dist");

ui_Dist_value = lv_label_create(ui_Distance);
lv_obj_set_width( ui_Dist_value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Dist_value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Dist_value, 0 );
lv_obj_set_y( ui_Dist_value, 20 );
lv_label_set_text(ui_Dist_value,"3 km");
lv_obj_set_style_text_font(ui_Dist_value, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button1 = lv_btn_create(ui_Screen2);
lv_obj_set_width( ui_Button1, 150);
lv_obj_set_height( ui_Button1, 50);
lv_obj_set_x( ui_Button1, 16 );
lv_obj_set_y( ui_Button1, 176 );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Button1, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Button1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Button1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Button1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Button1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Road_back_label = lv_label_create(ui_Button1);
lv_obj_set_width( ui_Road_back_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Road_back_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Road_back_label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Road_back_label,LV_SYMBOL_LEFT);
lv_obj_set_style_text_color(ui_Road_back_label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Road_back_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Road_back_label, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Clock_widget = lv_obj_create(ui_Screen2);
lv_obj_set_width( ui_Clock_widget, 128);
lv_obj_set_height( ui_Clock_widget, 120);
lv_obj_set_x( ui_Clock_widget, 176 );
lv_obj_set_y( ui_Clock_widget, 104 );
lv_obj_clear_flag( ui_Clock_widget, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Clock_widget, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Hours = lv_label_create(ui_Clock_widget);
lv_obj_set_width( ui_Hours, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Hours, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Hours, 8 );
lv_obj_set_y( ui_Hours, 8 );
lv_label_set_text(ui_Hours,"18");
lv_obj_set_style_text_color(ui_Hours, lv_color_hex(0x787878), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Hours, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Hours, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Minutes = lv_label_create(ui_Clock_widget);
lv_obj_set_width( ui_Minutes, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Minutes, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Minutes, -8 );
lv_obj_set_y( ui_Minutes, -8 );
lv_obj_set_align( ui_Minutes, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_Minutes,"56");
lv_obj_set_style_text_font(ui_Minutes, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}
