// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: LVGL_BIKE

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Battery_bg;
lv_obj_t *ui_Battery_Level;
lv_obj_t *ui_Charge_Icon;
lv_obj_t *ui_Charge_Progress;
lv_obj_t *ui_Light2;
lv_obj_t *ui_Light_Slider_2;
lv_obj_t *ui_Light1;
lv_obj_t *ui_Light_Slider_1;
lv_obj_t *ui_Light_Switch_1;
lv_obj_t *ui_Light_Switch_2;
lv_obj_t *ui_Speedometer;
lv_obj_t *ui_Speedometer_Arc;
lv_obj_t *ui_Speedometer_Label;
lv_obj_t *ui_Back_Tab;
lv_obj_t *ui_Back_Icon;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
