// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: LVGL_BIKE

#ifndef _LVGL_BIKE_UI_H
#define _LVGL_BIKE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Battery_bg;
extern lv_obj_t *ui_Battery_Level;
extern lv_obj_t *ui_Charge_Icon;
extern lv_obj_t *ui_Charge_Progress;
extern lv_obj_t *ui_Light2;
extern lv_obj_t *ui_Light_Slider_2;
extern lv_obj_t *ui_Light1;
extern lv_obj_t *ui_Light_Slider_1;
extern lv_obj_t *ui_Light_Switch_1;
extern lv_obj_t *ui_Light_Switch_2;
extern lv_obj_t *ui_Speedometer;
extern lv_obj_t *ui_Speedometer_Arc;
extern lv_obj_t *ui_Speedometer_Label;
extern lv_obj_t *ui_Dock;
void ui_event_RoadApp( lv_event_t * e);
extern lv_obj_t *ui_RoadApp;
extern lv_obj_t *ui_RAppLabel;
extern lv_obj_t *ui_SettingsApp;
extern lv_obj_t *ui_SAppLabel;
extern lv_obj_t *ui_NaviApp;
extern lv_obj_t *ui_NAppLabel;
extern lv_obj_t *ui_ClockApp;
extern lv_obj_t *ui_CAppLabel;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_Speedometer2;
extern lv_obj_t *ui_Speedometer_Arc1;
extern lv_obj_t *ui_Speedometer_Label1;
extern lv_obj_t *ui_Kmh_label;
extern lv_obj_t *ui_Distance;
extern lv_obj_t *ui_Dist_label;
extern lv_obj_t *ui_Dist_value;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Road_back_label;
extern lv_obj_t *ui_Clock_widget;
extern lv_obj_t *ui_Hours;
extern lv_obj_t *ui_Minutes;
extern lv_obj_t *ui____initial_actions0;



LV_FONT_DECLARE( ui_font_seven_segment);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
