// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: LVGL_BIKE

#ifndef _LVGL_BIKE_UI_H
#define _LVGL_BIKE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_MainApp
void ui_MainApp_screen_init(void);
extern lv_obj_t * ui_MainApp;
extern lv_obj_t * ui_Main_Bat_bg;
extern lv_obj_t * ui_Main_Bat_Lv;
extern lv_obj_t * ui_Main_Charge_Icon;
extern lv_obj_t * ui_Main_Charge_Prog;
extern lv_obj_t * ui_Main_Light2;
extern lv_obj_t * ui_Main_Light2_Slider;
extern lv_obj_t * ui_Main_Light1;
extern lv_obj_t * ui_Main_Light1_Slider;
extern lv_obj_t * ui_Main_Light1_Swt;
extern lv_obj_t * ui_Main_Light2_Swt;
extern lv_obj_t * ui_Main_Speed;
extern lv_obj_t * ui_Main_Speed_Arc;
extern lv_obj_t * ui_Main_Speed_Label;
extern lv_obj_t * ui_Main_Dock;
void ui_event_Main_RoadApp(lv_event_t * e);
extern lv_obj_t * ui_Main_RoadApp;
extern lv_obj_t * ui_Main_RoadApp_Icon;
void ui_event_Main_SetApp(lv_event_t * e);
extern lv_obj_t * ui_Main_SetApp;
extern lv_obj_t * ui_Main_SetApp_Icon;
extern lv_obj_t * ui_Main_NaviApp;
extern lv_obj_t * ui_Main_NaviApp_Icon;
extern lv_obj_t * ui_Main_ClockApp;
extern lv_obj_t * ui_Main_ClockApp_Icon;
// SCREEN: ui_RoadApp
void ui_RoadApp_screen_init(void);
extern lv_obj_t * ui_RoadApp;
extern lv_obj_t * ui_Road_Speed;
extern lv_obj_t * ui_Road_Speed_Arc;
extern lv_obj_t * ui_Road_Speed_Label;
extern lv_obj_t * ui_Road_Kmh_Label;
extern lv_obj_t * ui_Road_Dist;
extern lv_obj_t * ui_Road_Dist_Label;
extern lv_obj_t * ui_Road_Dist_Value;
void ui_event_Road_Back_Btn(lv_event_t * e);
extern lv_obj_t * ui_Road_Back_Btn;
extern lv_obj_t * ui_Road_Back_Label;
extern lv_obj_t * ui_Road_Clock;
extern lv_obj_t * ui_Road_Clock_Hours;
extern lv_obj_t * ui_Road_Clock_Minutes;
// SCREEN: ui_SettingsApp
void ui_SettingsApp_screen_init(void);
extern lv_obj_t * ui_SettingsApp;
extern lv_obj_t * ui_Set_TopBar;
extern lv_obj_t * ui_Set_TopLabel;
extern lv_obj_t * ui_Set_TopIcon;
void ui_event_Set_TopBackBtn(lv_event_t * e);
extern lv_obj_t * ui_Set_TopBackBtn;
extern lv_obj_t * ui_Set_TopBackBtn_Label;
extern lv_obj_t * ui_Set_Main;
extern lv_obj_t * ui_Set_Entry_ClearDist;
extern lv_obj_t * ui_Set_Entry_ClearDist_Label;
extern lv_obj_t * ui_Set_Entry_ClearDist_Btn;
extern lv_obj_t * ui_Set_Entry_ClearDist_Btn_Label;
extern lv_obj_t * ui_Set_Entry_SetWheelLen;
extern lv_obj_t * ui_Set_Entry_SetWheelLen_Label;
extern lv_obj_t * ui_Set_Entry_SetWheelLen_Spin;
void ui_event_Set_Entry_SetWheelLen_Plus(lv_event_t * e);
extern lv_obj_t * ui_Set_Entry_SetWheelLen_Plus;
extern lv_obj_t * ui_Set_Entry_SetWheelLen_Plus_Label;
void ui_event_Set_Entry_SetWheelLen_Minus(lv_event_t * e);
extern lv_obj_t * ui_Set_Entry_SetWheelLen_Minus;
extern lv_obj_t * ui_Set_Entry_SetWheelLen_Minus_Label;
extern lv_obj_t * ui____initial_actions0;





LV_FONT_DECLARE(ui_font_seven_segment);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
